apiVersion: v1
entries:
  csi-driver-nfs:
  - apiVersion: v1
    appVersion: latest
    created: "2021-02-24T13:27:32.135146481Z"
    description: CSI NFS Driver for Kubernetes
    digest: 0310b07ac757b0f26eecb6aba5beea1377189b9df4864cfdbbd6879243d511e0
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/latest/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v3.0.0
    created: "2021-02-24T13:27:32.135892285Z"
    description: CSI NFS Driver for Kubernetes
    digest: 092ff0377bbbc6ebfba97870c1eaec557aaf62626777d8b5f8343888af2a5506
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
    version: v3.0.0
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2021-02-24T13:27:32.135498883Z"
    description: CSI NFS Driver for Kubernetes
    digest: f537a133eaa965f1c053ffac130f82c9b2b624e1f8bd42937c9c48818464eaac
    name: csi-driver-nfs
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
    version: v2.0.0
generated: "2021-02-24T13:27:32.134652878Z"
